### ISSUE TITLE
https://juliamolsim.org/   redirects to DFTK

### ISSUE THREAD

**Issue by cortner** [JuliaMolSim/JuliaMolSim.github.io#13] opened 2024-08-27 04:51 UTC
The web-address `https://juliamolsim.org/` is apparently linked to the DFTK repository instead of the JuliaMolSim Landing page.

**Comment by mfherbst** [comment] 2024-08-27 06:31
Really ... this is not intentional and funnily I cannot reproduce it on my end.

**Comment by cortner** [comment] 2024-08-27 14:34
maybe some problem in my browser cache? It happens on both of the browsers I have on my laptop and on my phone. Also - interestingly, both browsers first give me a warning that the site in unsecure, maybe because it redirects?

**Comment by rkurchin** [comment] 2024-08-28 18:37
A bunch of the workshop speakers/participants have been having issues resolving that URL and getting various warnings, but the `juliamolsim.github.io` one works fine. I've only been able to reproduce sporadically on my phone so also hard to figure out.

**Comment by cortner** [comment] 2024-08-28 18:40
> but the juliamolsim.github.io one works fine

yes, I can confirm that.

**Comment by mfherbst** [comment] 2024-10-24 09:56
Is this still an issue by the way. I recently changed something here.

**Closed as completed** 2024-10-24 13:07 UTC
